pose_names = {
    1: 'Akarna Dhanurasana',
    2: 'Bharadvajas Twist pose or Bharadvajasana I',
    3: 'Boat Pose or Paripurna Navasana',
    4: 'Bound Angle Pose or Baddha Konasana',
    5: 'Bow Pose or Dhanurasana',
    6: 'Bridge Pose or Setu Bandha Sarvangasana',
    7: 'Camel Pose or Ustrasana',
    8: 'Cat Cow Pose or Marjaryasana',
    9: 'Chair Pose or Utkatasana',
    10: 'Child Pose or Balasana',
    11: 'Cobra Pose or Bhujangasana',
    12: 'Cockerel Pose',
    13: 'Corpse Pose or Savasana',
    14: 'Cow Face Pose or Gomukhasana',
    15: 'Crane (Crow) Pose or Bakasana',
    16: 'Dolphin Plank Pose or Makara Adho Mukha Svanasana',
    17: 'Dolphin Pose or Ardha Pincha Mayurasana',
    18: 'Downward-Facing Dog pose or Adho Mukha Svanasana',
    19: 'Eagle Pose or Garudasana',
    20: 'Eight-Angle Pose or Astavakrasana',
    21: 'Extended Puppy Pose or Uttana Shishosana',
    22: 'Extended Revolved Side Angle Pose or Utthita Parsvakonasana',
    23: 'Extended Revolved Triangle Pose or Utthita Trikonasana',
    24: 'Feathered Peacock Pose or Pincha Mayurasana',
    25: 'Firefly Pose or Tittibhasana',
    26: 'Fish Pose or Matsyasana',
    27: 'Four-Limbed Staff Pose or Chaturanga Dandasana',
    28: 'Frog Pose or Bhekasana',
    29: 'Garland Pose or Malasana',
    30: 'Gate Pose or Parighasana',
    31: 'Half Lord of the Fishes Pose or Ardha Matsyendrasana',
    32: 'Half Moon Pose or Ardha Chandrasana',
    33: 'Handstand pose or Adho Mukha Vrksasana',
    34: 'Happy Baby Pose or Ananda Balasana',
    35: 'Head-to-Knee Forward Bend pose or Janu Sirsasana',
    36: 'Heron Pose or Krounchasana',
    37: 'Intense Side Stretch Pose or Parsvottanasana',
    38: 'Legs-Up-the-Wall Pose or Viparita Karani',
    39: 'Locust Pose or Salabhasana',
    40: 'Lord of the Dance Pose or Natarajasana',
    41: 'Low Lunge pose or Anjaneyasana',
    42: 'Noose Pose or Pasasana',
    43: 'Peacock Pose or Mayurasana',
    44: 'Pigeon Pose or Kapotasana',
    45: 'Plank Pose or Kumbhakasana',
    46: 'Plow Pose or Halasana',
    47: 'Pose Dedicated to the Sage Koundinya or Eka Pada Koundinyanasana I and II',
    48: 'Rajakapotasana',
    49: 'Reclining Hand-to-Big-Toe Pose or Supta Padangusthasana',
    50: 'Revolved Head-to-Knee Pose or Parivrtta Janu Sirsasana',
    51: 'Scale Pose or Tolasana',
    52: 'Scorpion pose or Vrischikasana',
    53: 'Seated Forward Bend pose or Paschimottanasana',
    54: 'Shoulder-Pressing Pose or Bhujapidasana',
    55: 'Side-Reclining Leg Lift pose or Anantasana',
    56: 'Side Crane (Crow) Pose or Parsva Bakasana',
    57: 'Side Plank Pose or Vasisthasana',
    58: 'Sitting pose 1 (normal)',
    59: 'Split pose',
    60: 'Staff Pose or Dandasana',
    61: 'Standing Forward Bend pose or Uttanasana',
    62: 'Standing Split pose or Urdhva Prasarita Eka Padasana',
    63: 'Standing Big Toe Hold pose or Utthita Padangusthasana',
    64: 'Supported Headstand pose or Salamba Sirsasana',
    65: 'Supported Shoulderstand pose or Salamba Sarvangasana',
    66: 'Supta Baddha Konasana',
    67: 'Supta Virasana Vajrasana',
    68: 'Tortoise Pose',
    69: 'Tree Pose or Vrksasana',
    70: 'Upward Bow (Wheel) Pose or Urdhva Dhanurasana',
    71: 'Upward Facing Two-Foot Staff Pose or Dwi Pada Viparita Dandasana',
    72: 'Upward Plank Pose or Purvottanasana',
    73: 'Virasana or Vajrasana',
    74: 'Warrior III Pose or Virabhadrasana III',
    75: 'Warrior II Pose or Virabhadrasana II',
    76: 'Warrior I Pose or Virabhadrasana I',
    77: 'Wide-Angle Seated Forward Bend pose or Upavistha Konasana',
    78: 'Wide-Legged Forward Bend pose or Prasarita Padottanasana',
    79: 'Wild Thing pose or Camatkarasana',
    80: 'Wind Relieving pose or Pawanmuktasana',
    81: 'Yogic Sleep Pose',
    82: 'Viparita Virabhadrasana or Reverse Warrior Pose',
}
